name: Docker containers

on: push

jobs:
  docker-steps:
    runs-on: ubuntu-latest
    container:
      image:  node:16-stretch-slim
    steps:
      - name: log node version
        run: node -v
      - name: steps with docker
        uses: docker://node: 12.14.1-alpine3.10
        with:
          entrypoint: /bin/echo
          args: 'Hello World' 
      - name: steps with docker
        uses: docker://node: 12.14.1-alpine3.10
        with:
          entrypoint: /usr/local/bin/node
          args: -v
  node-docker:
    runs-on: ubuntu-latest
    container: 
      image: node:14-alpine3.14
    steps:
      - name: Log node version
        run: |
          node -v
          cat /etc/os-release