name: matrix

on: push

jobs:
  node-versions:
    strategy:
      matrix:
        os:[ubuntu-latest, windows-latest]
        node_version: [6, 8, 10] # All steps should run each version and os
    runs-on: ${{ matrix.os}}
    steps:
        - name: log node version
          run: node -v
        - uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node_version }}
        - name: log node version
          run: node -v